@baseUrl = http://localhost:3000


### Get all films
GET {{baseUrl}}/films

### GET one film
GET {{baseUrl}}/films/4

### Create a film
POST {{baseUrl}}/films
Content-Type: application/json

{
    "title":"I HATE JAVASCRIPT FROM THE BOTTOM OF MY HEART, GIVE ME PLAIN JAVA PLS SEND HELP",
    "duration":"120",
    "budget":"0",
    "link":"https://e-vinci.github.io/web2/"
}